### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [Cylix/Reflex#2]
Would you like to [replace any double quotes](https://github.com/Cylix/Reflex/blob/3e73595e30ac99aff6caaa77117b92ca58029ccf/includes/reflex/reflection_manager.hpp#L7) by [angle brackets around file names for include statements](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename)?

**Comment by Cylix** [comment]
Done, thanks for the suggestion! It's better especially since the library is "headers only".

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/Cylix/Reflex/commit/b51433f6f07e88d5b167ea71f481aa685bedcb86).
