### ISSUE TITLE
not enough actual parameters for macro '__REFLEX_GET_MACRO_3'

### ISSUE THREAD

**Issue by meruiden** [Cylix/Reflex#3]
I get this weird error in visual studio 2017 when I try to compile the examples

**Comment by Cylix** [comment]
Hi,

Do you have a code example that triggered that error?

`__REFLEX_GET_MACRO_3` is a macro used by `REGISTER_CLASS_FUNCTIONS`.
`REGISTER_CLASS_FUNCTIONS` can either be used for non-namespaced class methods `REGISTER_CLASS_FUNCTIONS (ClassName, (fct1)(fct2))` or namespaced class methods `REGISTER_CLASS_FUNCTIONS (Namespace, ClassName, (fct1)(fct2))`.

If there are less than two parameters, then __REFLEX_GET_MACRO_3 will be called with an insufficient number of parameters and will fail.

Best,

**Comment by Cylix** [comment]
In the absence of reply during the past 2 weeks, I'm closing this issue.
However, feel free to re-open it if you need to.

Best,
